### PR TITLE
Redesigns slides!

### PR DESCRIPTION
**Pull request by PTNobel**
I made some changes to the Beamer theme. Also adds some dummy content to mt2.tex.

The main controversial choice I made (controversial being George doesn't like) is switching to a font with sans serif math which I think looks much better.

### CODE REVIEW

**Comment by PTNobel** [comment]
[mt2(1).pdf](https://github.com/hkntutoring/ee16b-mt2-review/files/2994504/mt2.1.pdf)

**Comment by PTNobel** [comment]
Blocked by #1

**Comment by guor8lei** [comment]
I personally think that serif fonts may look better for the math equations, but that is just my personal opinion.

**Comment by PTNobel** [comment]
I always have the feeling that consistent fonts look better and I think the math font used here still looks good. Especially when you have math interspersed with text.

**Comment by PTNobel** [comment]
[mt2.pdf](https://github.com/hkntutoring/ee16b-mt2-review/files/3046504/mt2.pdf)

Here's the new design. (I also corrected the solution to the diff eq as desired).

**Pull request merged**
